#!/bin/bash
#set -ex

# Enable the proxy extension in notebook and lab
#jupyter serverextension enable --py jupyter_server_proxy
#jupyter labextension install @jupyterlab/server-proxy
#jupyter lab build

wget https://open-vsx.org/api/gitduck/code-streaming/0.1.26/file/gitduck.code-streaming-0.1.26.vsix
wget https://open-vsx.org/api/ms-python/python/2020.8.105369/file/ms-python.python-2020.8.105369.vsix

#code-server --install-extension ms-python.python-2020.8.105369.vsix
#code-server --install-extension gitduck.code-streaming-0.1.26.vsix


#export SERVICE_URL=https://open-vsx.org/vscode/gallery
#export ITEM_URL=https://open-vsx.org/vscode/item
#code-server --install-extension gitduck.code-streaming

# Install the VS code proxy
pip install -e.
